# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0.xci
# IP: The module: 'BlkGPIO_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlkGPIO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlkGPIO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlkGPIO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0.xci
# IP: The module: 'BlkGPIO_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlkGPIO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlkGPIO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/narendiran/Desktop/AXILearning/VivadoProjects/MasterAXIGPIO/MasterAXIGPIO.srcs/sources_1/bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlkGPIO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
