#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 08 06:15:23 IST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim TB_SlaveReadFrom3Reg_behav -key {Behavioral:sim_1:Functional:TB_SlaveReadFrom3Reg} -tclbatch TB_SlaveReadFrom3Reg.tcl -protoinst "protoinst_files/SingleWriteBRAM.protoinst" -protoinst "protoinst_files/SingleReadBRAM.protoinst" -protoinst "protoinst_files/SlaveWriteTo3Reg.protoinst" -protoinst "protoinst_files/SlaveReadFrom3Reg.protoinst" -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/SingleReadBRAM_waveform.wcfg -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/SingleWriteBRAM_waveform.wcfg -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/TB_SlaveWriteTo3Reg_waveform.wcfg -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/SlaveReadFrom3Reg_waveform.wcfg -log simulate.log"
xsim TB_SlaveReadFrom3Reg_behav -key {Behavioral:sim_1:Functional:TB_SlaveReadFrom3Reg} -tclbatch TB_SlaveReadFrom3Reg.tcl -protoinst "protoinst_files/SingleWriteBRAM.protoinst" -protoinst "protoinst_files/SingleReadBRAM.protoinst" -protoinst "protoinst_files/SlaveWriteTo3Reg.protoinst" -protoinst "protoinst_files/SlaveReadFrom3Reg.protoinst" -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/SingleReadBRAM_waveform.wcfg -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/SingleWriteBRAM_waveform.wcfg -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/TB_SlaveWriteTo3Reg_waveform.wcfg -view /home/narendiran/Desktop/AXILearning/AXIProjectSources/SlaveReadFrom3Reg_waveform.wcfg -log simulate.log

