#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jun 04 07:09:23 IST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e438ba73389e42ed8101cefab9aacf49 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_3 -L axi_bram_ctrl_v4_1_1 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tbBRAMwriteToBRAMusingMaster_behav xil_defaultlib.tbBRAMwriteToBRAMusingMaster xil_defaultlib.glbl -log elaborate.log"
xelab -wto e438ba73389e42ed8101cefab9aacf49 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_3 -L axi_bram_ctrl_v4_1_1 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tbBRAMwriteToBRAMusingMaster_behav xil_defaultlib.tbBRAMwriteToBRAMusingMaster xil_defaultlib.glbl -log elaborate.log

