#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jun 04 07:09:33 IST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tbBRAMwriteToBRAMusingMaster_behav -key {Behavioral:sim_1:Functional:tbBRAMwriteToBRAMusingMaster} -tclbatch tbBRAMwriteToBRAMusingMaster.tcl -protoinst "protoinst_files/BlkBRAMWriteUsingMaster.protoinst" -log simulate.log"
xsim tbBRAMwriteToBRAMusingMaster_behav -key {Behavioral:sim_1:Functional:tbBRAMwriteToBRAMusingMaster} -tclbatch tbBRAMwriteToBRAMusingMaster.tcl -protoinst "protoinst_files/BlkBRAMWriteUsingMaster.protoinst" -log simulate.log

