set_property PACKAGE_PIN Y16 [get_ports initializeOperation]
set_property IOSTANDARD LVCMOS33 [get_ports initializeOperation]
set_property PACKAGE_PIN R18 [get_ports resetN]
set_property PACKAGE_PIN L16 [get_ports clkIn]
set_property IOSTANDARD LVCMOS33 [get_ports clkIn]
set_property IOSTANDARD LVCMOS33 [get_ports resetN]


create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clkIn]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_4bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_4bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_4bits_tri_o[1]}]
set_property IOSTANDARD LVTTL [get_ports {leds_4bits_tri_o[0]}]
set_property PACKAGE_PIN D18 [get_ports {leds_4bits_tri_o[3]}]
set_property PACKAGE_PIN G14 [get_ports {leds_4bits_tri_o[2]}]
set_property PACKAGE_PIN M15 [get_ports {leds_4bits_tri_o[1]}]
set_property PACKAGE_PIN M14 [get_ports {leds_4bits_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sw_4bits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_4bits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_4bits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_4bits[0]}]
set_property PACKAGE_PIN G15 [get_ports {sw_4bits[0]}]
set_property PACKAGE_PIN P15 [get_ports {sw_4bits[1]}]
set_property PACKAGE_PIN W13 [get_ports {sw_4bits[2]}]
set_property PACKAGE_PIN T16 [get_ports {sw_4bits[3]}]
