# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constFIle.xdc

# Block Designs: bd/BlkGPIO/BlkGPIO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO || ORIG_REF_NAME==BlkGPIO} -quiet] -quiet

# IP: bd/BlkGPIO/ip/BlkGPIO_axi_gpio_0_0/BlkGPIO_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO_axi_gpio_0_0 || ORIG_REF_NAME==BlkGPIO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/BlkGPIO/ip/BlkGPIO_MasterWriteToBRAM_0_0/BlkGPIO_MasterWriteToBRAM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO_MasterWriteToBRAM_0_0 || ORIG_REF_NAME==BlkGPIO_MasterWriteToBRAM_0_0} -quiet] -quiet

# IP: bd/BlkGPIO/ip/BlkGPIO_xlconstant_0_0/BlkGPIO_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO_xlconstant_0_0 || ORIG_REF_NAME==BlkGPIO_xlconstant_0_0} -quiet] -quiet

# IP: bd/BlkGPIO/ip/BlkGPIO_ResetNotGate_0_0/BlkGPIO_ResetNotGate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO_ResetNotGate_0_0 || ORIG_REF_NAME==BlkGPIO_ResetNotGate_0_0} -quiet] -quiet

# IP: bd/BlkGPIO/ip/BlkGPIO_MasterReadFromBram_0_0/BlkGPIO_MasterReadFromBram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO_MasterReadFromBram_0_0 || ORIG_REF_NAME==BlkGPIO_MasterReadFromBram_0_0} -quiet] -quiet

# IP: bd/BlkGPIO/ip/BlkGPIO_axi_gpio_1_0/BlkGPIO_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkGPIO_axi_gpio_1_0 || ORIG_REF_NAME==BlkGPIO_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/BlkGPIO/BlkGPIO_ooc.xdc
